//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/InputSystem/Titan.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TitanInputMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TitanInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Titan"",
    ""maps"": [
        {
            ""name"": ""VanguardTitan"",
            ""id"": ""e4d377fb-3abb-4eaa-8b66-27ffb927f0a6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""aa56b7c1-d0fc-4577-992e-15ba686e4227"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""cad44aee-3577-4348-936e-7c12dea44cb6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Value"",
                    ""id"": ""62b99f8f-4795-49b8-b41e-4c2ebf01db36"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""e6336dc4-112f-4dfd-8638-d2be161d1f31"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Value"",
                    ""id"": ""ea94c48b-e4e0-4e57-a236-881ea508d87c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Value"",
                    ""id"": ""7afcc6ba-06d4-4927-881f-e35f18eeaf17"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Value"",
                    ""id"": ""b1047e08-c721-4575-a95a-9e1779b10c76"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""12ee967f-f36a-450a-b1e7-54f3deccba4f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d55dd94d-0a49-4f98-ae8a-6efdc0a4ae8e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f52cf3eb-0e0d-4ada-9549-bd37fdf0f592"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""271e7d6f-1514-467c-a718-00f27994c1ed"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9adb7c91-8f66-48a3-b680-7e7388627a2f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""08b726c3-ea94-4318-a412-4465989793ad"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""349ac228-af98-4fc4-af6e-3e4840c01fa5"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc61bb1a-78b4-4729-a81e-6cd53d01e016"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2afea39-d8f6-4826-885f-f68c804119f5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec190de8-ad35-464d-bdc4-e161e5c7a50e"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c5ed463-f018-41d9-9bd5-f8b130252e12"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VanguardTitan
        m_VanguardTitan = asset.FindActionMap("VanguardTitan", throwIfNotFound: true);
        m_VanguardTitan_Move = m_VanguardTitan.FindAction("Move", throwIfNotFound: true);
        m_VanguardTitan_Look = m_VanguardTitan.FindAction("Look", throwIfNotFound: true);
        m_VanguardTitan_Sprint = m_VanguardTitan.FindAction("Sprint", throwIfNotFound: true);
        m_VanguardTitan_Walk = m_VanguardTitan.FindAction("Walk", throwIfNotFound: true);
        m_VanguardTitan_Fire = m_VanguardTitan.FindAction("Fire", throwIfNotFound: true);
        m_VanguardTitan_Reload = m_VanguardTitan.FindAction("Reload", throwIfNotFound: true);
        m_VanguardTitan_Dash = m_VanguardTitan.FindAction("Dash", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VanguardTitan
    private readonly InputActionMap m_VanguardTitan;
    private IVanguardTitanActions m_VanguardTitanActionsCallbackInterface;
    private readonly InputAction m_VanguardTitan_Move;
    private readonly InputAction m_VanguardTitan_Look;
    private readonly InputAction m_VanguardTitan_Sprint;
    private readonly InputAction m_VanguardTitan_Walk;
    private readonly InputAction m_VanguardTitan_Fire;
    private readonly InputAction m_VanguardTitan_Reload;
    private readonly InputAction m_VanguardTitan_Dash;
    public struct VanguardTitanActions
    {
        private @TitanInputMap m_Wrapper;
        public VanguardTitanActions(@TitanInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_VanguardTitan_Move;
        public InputAction @Look => m_Wrapper.m_VanguardTitan_Look;
        public InputAction @Sprint => m_Wrapper.m_VanguardTitan_Sprint;
        public InputAction @Walk => m_Wrapper.m_VanguardTitan_Walk;
        public InputAction @Fire => m_Wrapper.m_VanguardTitan_Fire;
        public InputAction @Reload => m_Wrapper.m_VanguardTitan_Reload;
        public InputAction @Dash => m_Wrapper.m_VanguardTitan_Dash;
        public InputActionMap Get() { return m_Wrapper.m_VanguardTitan; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VanguardTitanActions set) { return set.Get(); }
        public void SetCallbacks(IVanguardTitanActions instance)
        {
            if (m_Wrapper.m_VanguardTitanActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnLook;
                @Sprint.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnSprint;
                @Walk.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnWalk;
                @Fire.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnFire;
                @Reload.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnReload;
                @Dash.started -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_VanguardTitanActionsCallbackInterface.OnDash;
            }
            m_Wrapper.m_VanguardTitanActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
            }
        }
    }
    public VanguardTitanActions @VanguardTitan => new VanguardTitanActions(this);
    public interface IVanguardTitanActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
    }
}
